### ISSUE TITLE
recompose.parser.Parser$ParserException: Unknown drawable format: @color/white

### ISSUE THREAD

**Issue by e-tverdokhleb** [pocmo/recompose#111]
Hi, tnx for plugin, 
is it possible to fix this error:

recompose.parser.Parser$ParserException: Unknown size value: @dimen/common_margin
	at recompose.parser.values.SizeKt.size(Size.kt:31)
	at recompose.parser.values.PaddingKt.padding(Padding.kt:29)
	at recompose.parser.xml.ViewKt.viewAttributes(View.kt:82)
	at recompose.parser.xml.viewgroup.LinearLayoutKt.linearLayout(LinearLayout.kt:33)
	at recompose.parser.xml.ViewKt.node(View.kt:51)
	at recompose.parser.xml.ViewGroupKt.viewGroupAttributes(ViewGroup.kt:37)
	at recompose.parser.xml.viewgroup.UnknownKt.unknown(Unknown.kt:31)
	at recompose.parser.xml.ViewKt.node(View.kt:69)
	at recompose.parser.xml.ViewGroupKt.viewGroupAttributes(ViewGroup.kt:37)
	at recompose.parser.xml.viewgroup.ConstraintLayoutKt.constraintLayout(ConstraintLayout.kt:32)
	at recompose.parser.xml.ViewKt.node(View.kt:65)
	at recompose.parser.xml.ViewGroupKt.viewGroupAttributes(ViewGroup.kt:37)
	at recompose.parser.xml.viewgroup.UnknownKt.unknown(Unknown.kt:31)
	at recompose.parser.xml.ViewKt.node(View.kt:69)
	at recompose.parser.xml.LayoutKt.layout(Layout.kt:37)
	at recompose.parser.Parser.parse(Parser.kt:62)
	at recompose.parser.Parser.parse(Parser.kt:53)
	at recompose.parser.Parser.parse(Parser.kt:37)

**Comment by pocmo** [comment]
Hey! Yes, this looks like something we can fix (supporting dimensions as size attribute). The title of the bug seems to reference a different issue though (color <-> drawable) do you have a stacktrace for that too?
